name: News Summarizer Sentiment Analyzer

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  modelling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create gemini credentials.json
        run: echo '${{ secrets.CREDENTIAL_GEMINI }}' > credential_gemini.json

      - name: Create google sheets credentials.json
        run: echo '${{ secrets.CREDENTIAL_GOOGLE_SHEETS }}' > credential_google_sheets.json

      - name: Run summarizer and sentiment analyzer
        run: python news_summarizer_sentiment_analyzer.py
