name: Scrape Tradingview Overview

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.CREDENTIAL_MYSQL }}' > credential_mysql.json

      - name: Run scraper
        run: python scraping_tradingview_overview.py
