name: Fetch Yahoo Finance Data

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.CREDENTIAL_MYSQL }}' > credential_mysql.json

      - name: Run fetcher
        run: python yfinance_data_fetcher.py
